### ISSUE TITLE
你好，这个能作为server酱turbo版的下游服务吗？

### ISSUE THREAD

**Issue by goxofy** [easychen/telechan#1]

**Comment by easychen** [comment]
通过自定义消息通道应该可以进行配置。

![image](https://user-images.githubusercontent.com/1294760/115979147-d15b8900-a5b6-11eb-9033-a615c4f999c6.png)

**Comment by goxofy** [comment]
我之前就是在这里配置的，发现只能发get请求，post请求都不行
