### ISSUE TITLE
[Enhancement] Add `revoke` function to avoid message flooding via leaked sendkey 

### ISSUE THREAD

**Issue by ghost** [easychen/telechan#2]
希望机器人添加一个撤销 `sendkey` 的命令。

目前如果 `sendkey` 泄漏，就能一直给账号推送消息。而且我看了一下生成的 `sendkey` 也没有储存到数据库，没法在服务端从数据库里删除。

有段时间没用 Server 酱了，不清楚有没有类似的功能，Tele 酱里看代码没写这个功能，不过我对 TypeScript / JavaScript 不是很熟，直接提交 PR 是指望不上了。

**Comment by easychen** [comment]
目前Tele酱不存储sendkey，所以不能 revoke 。当前我自己的场景还是自搭自用，这种情况下，只需要修改配置文件中的随机字符串，就可以 revoke 全部的 sendkey。

等其他同学 PR吧
